# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  COVERITY_TOOL_HOME: $(Agent.BuildDirectory)/cov-analysis
  MAVEN_CACHE_FOLDER: $(Pipeline.Workspace)/.m2/repository
  MAVEN_OPTS: '-Dmaven.repo.local=$(MAVEN_CACHE_FOLDER)'

trigger:
- master
 

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    cd $(Agent.BuildDirectory)
    curl -s -L --user admin:coveritty -o license.dat http://35.223.17.182:8080/downloadFile.htm?fn=license.dat
    cat license.dat 
    

  displayName: 'Coverity Installed'



- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
