# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  COVERITY_TOOL_HOME: $(Agent.BuildDirectory)/cov-analysis
  MAVEN_CACHE_FOLDER: $(Pipeline.Workspace)/.m2/repository
  MAVEN_OPTS: '-Dmaven.repo.local=$(MAVEN_CACHE_FOLDER)'

trigger:
- master
 

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    cd $(Agent.BuildDirectory)
    curl -s -L --user admin:6cbf95e0f147564bba7611bab1971089 -o license.dat http://10.0.1.6:8080/downloadFile.htm?fn=license.dat
    curl -s -L --user admin:6cbf95e0f147564bba7611bab1971089 -o cov-analysis-linux64-2019.09.tar.gz http://10.0.1.6:8080/downloadFile.html?fn=cov-analysis-linux64-2019.09.tar.gz | tar -xvzf -
    ls -la
    mv cov-analysis-linux64-2019.09 cov-analysis
    cp license.dat ./cov-analysis/bin

  displayName: 'Coverity Installed'



- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
